spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/db2
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
#      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging.level:
  hello.itemservice.repository.mybatis: trace
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
mybatis:
  type-aliases-package: hello.itemservice.domain
  configuration:
    map-underscore-to-camel-case: true